HACK: audio_extn: Fix unused parameter warning in utils.c
The unused parameter warning appears if we are not building with SOUND_TRIGGER_ENABLED, which results in an unused 'snd_device'.

  hardware/qcom/audio/hal/audio_extn/utils.c:2522:55: error: unused parameter 'snd_device' [-Werror,-Wunused-parameter]
  void audio_extn_utils_release_snd_device(snd_device_t snd_device)
                                                      ^

Change-Id: Ia50282f5737518ea3eb1b0c74cb827362dbde679
Signed-off-by: Josh Choo <dev@joshchoo.com>